Дана целочисленная прямоугольная матрица. Определить кол-во столбцов, не содержащих ни одного нулевого элемента (оформить в виде функции). - сделано
Характеристикой строки целочисленной матрицы назовем сумму ее положительных четных элементов. Переставляя строки заданной матрицы, расположить их в соответствии с ростом характеристик (оформить в виде процедуры).

In [1]:
import numpy as np
sz = (4, 5)
ar = np.random.randint(-5, 10, size = sz)

Определить кол-во столбцов, не содержащих ни одного нулевого элемента

In [3]:
print(len(ar[np.where(ar.all(axis=1))]))

4


отдельный массив xar, в котором находятся характеристики каждой строки

In [5]:
temp = np.where((ar > 0) & ~(ar % 2), 1, 0) * ar
xar = temp.sum(axis=1)

Переставляя строки заданной матрицы, расположить их в соответствии с ростом характеристик

In [6]:
print(ar[xar.argsort()])


[[ 5 -3 -4 -1  5]
 [ 1  3  7 -4  1]
 [ 3  5  7  7  2]
 [-1  3  7 -3  4]]
